version: "3.9"

services:
  postgres_PR_db:
    image: postgres:16-alpine
    container_name: avi-postgres
    environment:
      POSTGRES_USER: admin_PR
      POSTGRES_PASSWORD: appPass_QWERTY
      POSTGRES_DB: PR_serv
    ports:
      - "5432:5432"
    volumes:
      - ./internal/db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_PR -d PR_serv"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: avi-app
    depends_on:
      postgres_PR_db:
        condition: service_healthy
    environment:
      HTTP_PORT: "8080"

      DB_HOST: postgres_PR_db
      DB_PORT: "5432"
      DB_USER: admin_PR
      DB_PASSWORD: appPass_QWERTY
      DB_NAME: PR_serv
      DB_SSLMODE: disable

    ports:
      - "8080:8080"
    restart: on-failure

  e2e:
    build:
      context: .
      target: builder
    profiles: [ "tests" ]
    depends_on:
      postgres_PR_db:
        condition: service_healthy
    environment:
      E2E_DSN: postgres://admin_PR:appPass_QWERTY@postgres_PR_db:5432/PR_serv?sslmode=disable
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    command: [ "go", "test", "-tags=e2e", "./test/e2e", "-v" ]

  k6:
    image: grafana/k6
    profiles: [ "tests" ]
    depends_on:
      app:
        condition: service_started
      e2e:
        condition: service_completed_successfully
    environment:
      BASE_URL: http://app:8080
    volumes:
      - ./test/load:/scripts:ro
    command: [ "run", "/scripts/k6_pr_scenario.js" ]


