version: "3.9"

services:
  postgres_PR_db:
    image: postgres:16-alpine
    container_name: avi-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./internal/db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: avi-app
    depends_on:
      postgres_PR_db:
        condition: service_healthy
    environment:
      HTTP_PORT: ${HTTP_PORT}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}

    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: on-failure

  e2e:
    build:
      context: .
      target: builder
    profiles: [ "tests" ]
    depends_on:
      postgres_PR_db:
        condition: service_healthy
    environment:
      E2E_DSN: postgres://admin_PR:appPass_QWERTY@postgres_PR_db:5432/PR_serv?sslmode=disable
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    command: [ "go", "test", "-tags=e2e", "./test/e2e", "-v" ]

  k6:
    image: grafana/k6
    profiles: [ "tests" ]
    depends_on:
      app:
        condition: service_started
      e2e:
        condition: service_completed_successfully
    environment:
      BASE_URL: http://app:${HTTP_PORT}
    volumes:
      - ./test/load:/scripts:ro
    command: [ "run", "/scripts/k6_pr_scenario.js" ]


